GET http://localhost:3001/api/users

### POST REGISTER
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "jethrocenas",
    "firstName": "luke",
    "lastName": "Luukkainen",
    "password": "password"
}

### POST LOGIN
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username" : "user1",
    "password": "password"
}

