GET http://localhost:3001/api/users

### POST REGISTER
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "luke 1",
    "name": "luke Luukkainen",
    "password": "salainen"
}

### POST LOGIN
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "salainen"
}
