
### Add Child
POST http://localhost:3001/api/trees/add-child
Content-Type: application/json

{
    "treeId": "66def91364fb2114901390e9",
    "nodeId": "66def91264fb2114901390e5",
    "childDetails": {
        "name": "Parent 2 Luukkainen",
        "birthdate": "2040-01-01T00:00:00.000Z",
        "deathdate": null
    }
}


### Add Parent
POST http://localhost:3001/api/trees/add-parent
Content-Type: application/json

{
    "treeId": "66def91664fb2114901390f3",
    "nodeId": "66def91664fb2114901390ef",
    "parentDetails": {
        "name": "Parent 2 Luukkainen",
        "birthdate": "2040-01-01T00:00:00.000Z",
        "deathdate": null
    }
}


### Check Relationship

GET http://localhost:3001/api/trees/check-relationship
Content-Type: application/json

{
    "referenceId": "66dc563cdd743679405e363c",
    "destinationId": "66dc565fdd743679405e3667"
}
