
### Add Child
POST http://localhost:3001/api/trees/add-child
Content-Type: application/json

{
    "treeId": "66f38d96d63361044b0181df",
    "nodeId": "66f38d96d63361044b0181db",
    "childDetails": {
        "name": "Grand Child",
        "birthdate": "2040-01-01T00:00:00.000Z",
        "deathdate": null
    }
}


### Add Parent
POST http://localhost:3001/api/trees/add-parent
Content-Type: application/json

{
    "treeId": "66f38d96d63361044b0181df",
    "nodeId": "66f38d96d63361044b0181db",
    "parentDetails": {
        "name": "Grand Child",
        "birthdate": "2040-01-01T00:00:00.000Z",
        "deathdate": null
    }
}


### Check Relationship

GET http://localhost:3001/api/trees/check-relationship
Content-Type: application/json

{
    "referenceId": "66e26abda048f0440e602594",
    "destinationId": "66f38e01d63361044b018209"
}
