### Add Child
POST http://localhost:3001/api/trees/add-child
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaXphIiwiaWQiOiI2NzUwMzFiM2MzYTVjZjI5NTY3MWFhMjYiLCJpYXQiOjE3MzMzMDg5MzUsImV4cCI6MTczMzM5NTMzNX0.3oOs-MHbNAGJwaDCLlb-MDVJgm02jiL2V4YPl6pSf_c
X-Tree-Id: 675031b3c3a5cf295671aa2c

{
    "nodeId": "675031b3c3a5cf295671aa2a",
    "childDetails": {
        "generalInformation": {
            "firstName": "Sample",
            "lastName": "Child"
        },
        "birthdate": "2040-01-01T00:00:00.000Z",
        "deathdate": null
    }
}

### Edit Node
PATCH http://localhost:3001/api/trees/update-node/674980a08b79e24e318a66b5
Content-Type: application/json

{
    "generalInformation": {
        "firstName": "Updated",
        "lastName": "Person",
        "birthdate": "2040-01-01T00:00:00.000Z"
    }
}

### Delete Node
DELETE http://localhost:3001/api/trees/delete-node/674981418b79e24e318a66d6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NzQ5NDkzNDY2OWY1ZDEzMDI4ZjJkMTciLCJpYXQiOjE3MzI4NjAwMTksImV4cCI6MTczMjg2MzYxOX0.yS5P1bjX_7hBRkS4sip5_TosZMXfxtz0sE3cm-CUd8g 


### Add Parent
POST http://localhost:3001/api/trees/add-parent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NzQ5NDkzNDY2OWY1ZDEzMDI4ZjJkMTciLCJpYXQiOjE3MzI4NjAwMTksImV4cCI6MTczMjg2MzYxOX0.yS5P1bjX_7hBRkS4sip5_TosZMXfxtz0sE3cm-CUd8g 
X-Tree-Id: 67494934669f5d13028f2d1d

{
    "nodeId": "67494934669f5d13028f2d1b",
    "parentDetails": {
        "generalInformation": {
            "fistName": "Sample",
            "lastName": "Parent"
        },
        "birthdate": "2040-01-01T00:00:00.000Z",
        "deathdate": null
    }
}

### Check Relationship
GET http://localhost:3001/api/trees/check-relationship
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NzI2NGI3OTY5NmFlNjBiZDc4NDdiZGUiLCJpYXQiOjE3MzA1OTkyNTIsImV4cCI6MTczMDYwMjg1Mn0.LhTV7SqoYf2zVG8h56Jt06-BnkwZRJXdX7XerzZ9hc8
X-Tree-Id: 67264b79696ae60bd7847be4

{
    "referenceId": "67264b79696ae60bd7847be2",
    "destinationId": "67264ee5f00892aa2bf642e6"
}



### GET TREE   
GET http://localhost:3001/api/trees/family-tree/67494934669f5d13028f2d17
Content-Type: application/json

