### Add Child
POST http://localhost:3001/api/trees/add-child
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpldGhybyIsImlkIjoiNjc1MDVjYWI2NDdiY2VkY2U2NjJkZTgwIiwiaWF0IjoxNzMzMzE5OTIxLCJleHAiOjE3MzM0MDYzMjF9.woo4ObLt8V4lIvoBKl0I0ZdbjQkdl6JPPPzzsFYzPas
X-Tree-Id: 67505cab647bcedce662de86

{
    "nodeId": "67505cab647bcedce662de84",
    "childDetails": {
        "generalInformation": {
            "firstName": "Sample",
            "lastName": "Child"
        },
        "birthdate": "2040-01-01T00:00:00.000Z",
        "deathdate": null
    }
}

### Edit Node
PATCH http://localhost:3001/api/trees/update-node/674980a08b79e24e318a66b5
Content-Type: application/json

{
    "generalInformation": {
        "firstName": "Updated",
        "lastName": "Person",
        "birthdate": "2040-01-01T00:00:00.000Z"
    }
}

### Delete Node
DELETE http://localhost:3001/api/trees/delete-node/674981418b79e24e318a66d6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NzQ5NDkzNDY2OWY1ZDEzMDI4ZjJkMTciLCJpYXQiOjE3MzI4NjAwMTksImV4cCI6MTczMjg2MzYxOX0.yS5P1bjX_7hBRkS4sip5_TosZMXfxtz0sE3cm-CUd8g 


### Add Parent
POST http://localhost:3001/api/trees/add-parent
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lb3dlcnoiLCJpZCI6IjY3NTI5MDhiZjlkZWRkNGU2M2Q1NGQ2MSIsImlhdCI6MTczMzU4NjY4NiwiZXhwIjoxNzMzNjczMDg2fQ.fsgIhIcaN_36GB8JlR7TRIYPloepiv75NTZ1Kq2pRmk
X-Tree-Id: 6752908df9dedd4e63d54d78

{
    "nodeId": "6752908df9dedd4e63d54d6e",
    "parentDetails": {
        "generalInformation": {
            "firstName": "Sample",
            "lastName": "Parent"
        },
        "birthdate": "2040-01-01T00:00:00.000Z",
        "deathdate": null
    }
}

### Check Relationship
GET http://localhost:3001/api/trees/check-relationship
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NzI2NGI3OTY5NmFlNjBiZDc4NDdiZGUiLCJpYXQiOjE3MzA1OTkyNTIsImV4cCI6MTczMDYwMjg1Mn0.LhTV7SqoYf2zVG8h56Jt06-BnkwZRJXdX7XerzZ9hc8
X-Tree-Id: 67264b79696ae60bd7847be4

{
    "referenceId": "67264b79696ae60bd7847be2",
    "destinationId": "67264ee5f00892aa2bf642e6"
}



### GET TREE   
GET http://localhost:3001/api/trees/family-tree/6752908bf9dedd4e63d54d61
Content-Type: application/json

